absolute: true  # Force absolute comparison for cardboardlint
project:
  name: iodata
  requirements: [
    # pylint 2.7.2 hangs on tools/harmonics.py
    [pylint !=2.7.2, pylint !=2.7.2],
    [sympy, sympy],
  ]
  packages:
    - dist_name: qc-iodata
      tools:
        - write-py-version
        - cardboardlint-static
        - build-py-inplace
        - cardboardlint-dynamic
        - pytest
        - upload-codecov
        - build-sphinx-doc
        - upload-docs-gh
        - build-py-source
        - build-conda
        - deploy-pypi
        - deploy-conda
        - deploy-github
