package:
  version: "{{ PROJECT_VERSION }}"
  name: 'iodata'

source:
  path: ../../

build:
  number: 0
  string: py{{ CONDA_PY }}_1
  script:
    - export CFLAGS="${CFLAGS} -isysroot ${CONDA_BUILD_SYSROOT}"  # [osx]
    - python setup.py build_ext -I {{ PREFIX }}/include
    - python setup.py install --single-version-externally-managed --record=record.txt
  entry_points:
    - iodata-convert = iodata.__main__:main

requirements:
  build:
    - {{ compiler("c") }}
  host:
    - python
    - numpy >=1.0
    - cython >=0.24.1
    - setuptools
  run:
    - python
    - scipy
    - attrs >=19.1.0
    - importlib_resources  # [py<37]

test:
  requires:
    - python
    - pytest
    - pytest-xdist <2.0.0
  imports:
    - iodata
  commands:
    - conda inspect linkages iodata
    - pytest --pyargs iodata -v -n auto

about:
  home: https://github.com/theochem/iodata
  license: GNU Version 3
