package:
  version: "{{ PROJECT_VERSION }}"
  name: 'iodata'

source:
  path: ../../

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps"
  entry_points:
    - iodata-convert = iodata.__main__:main

requirements:
  host:
    - python
    - numpy >=1.0
    - setuptools
  run:
    - python
    - scipy
    - attrs >=20.1.0
    - importlib_resources  # [py<37]

test:
  requires:
    - python
    - pytest
    - pytest-xdist
  imports:
    - iodata
  commands:
    - pytest --pyargs iodata -v -n auto

about:
  description: Input and output module for quantum chemistry
  home: https://iodata.readthedocs.io/en/latest
  doc_url: https://iodata.readthedocs.io/en/latest
  dev_url: https://github.com/theochem/iodata
  license: GNU Version 3
  license_family: GPL
  license_file: LICENSE
